version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations:ro
#
#  api:
#    build: .
#    env_file: .env.example
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    command: [ "/bin/sh", "/app/entrypoint.sh" ]
#    # command: [ "/bin/sh", "-c", "/app/scripts/wait-for.sh postgres:5432 -- ./service-catalog" ]
##    volumes:
##      - ./:/app:cached

volumes:
  pgdata:
